### ISSUE TITLE
[BUG] Caesar Cipher couldn't decrypt

### ISSUE THREAD

**Issue by dubeyanant** [inclinedadarsh/ciphered#3] opened 2023-11-07 19:39 UTC
**Describe the bug**
doesn't work.

**To Reproduce**
Algo: Caesar Cipher
Key: 32
Plain text: Hellow
Ciphered text: Nkrruc
Returned decrypted text: Hello]

**Comment by inclinedadarsh** [comment] 2023-11-08 12:27
Thanks @dubeyanant for finding the bug.

Would you like to work on this?

**Comment by dubeyanant** [comment] 2023-11-08 15:02
Sure!

**Comment by inclinedadarsh** [comment] 2023-11-08 16:32
That's great!
The issue is in this file: https://github.com/inclinedadarsh/ciphered/blob/main/src/lib/algorithms/caesar-cipher.ts
Specifically in the decrypt method.

Have a look at it and let me know if you need any other help.
I'm assigning this to you.

**Comment by inclinedadarsh** [comment] 2023-11-10 13:48
Thanks a lot for the contribution @dubeyanant

**Closed by inclinedadarsh** 2023-11-10 13:48 UTC
Labels: bug, help wanted, algorithm
